const FETCHING_DATA = 'FETCHING_DATA'
const FETCH_SUCESS = 'FETCHING_SUCESS'
const FETCHING_ERROR = 'FETCHING_ERROR'
const RESET = 'RESET'

export {FETCHING_DATA, FETCH_SUCESS, FETCHING_ERROR, RESET};